### ISSUE TITLE
How to set width and height?

### ISSUE THREAD

**Issue by iamdubx** [creotip/vue-particles#13]
I want to make it fullscreen, how to do that?

UPD. I was able to set it fullscreen by adding this

```
.particles-wrapper {
  position: absolute;
  top: 0;
  width: 100%;
  height: 100vh;
}

#particles-js {
  width: 100%;
  height: 100vh;
}
```
But it doesn't seems like a native solution.

**Comment by iamdubx** [comment]
Ok, so if I am getting right, it's the only way, there's no bindings in attributes for that.

**Comment by IsmaelSos** [comment]
> Quiero que sea a pantalla completa, ¿cómo hacer eso?
> 
> UPD. Pude configurarlo en pantalla completa al agregar esto
> 
> ```
> .particles-wrapper {
>   position: absolute;
>   top: 0;
>   width: 100%;
>   height: 100vh;
> }
> 
> #particles-js {
>   width: 100%;
>   height: 100vh;
> }
> ```
> Pero no parece una solución nativa.

Hi, where do you add that code? Thank you!
