### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by Sodininkas** [creotip/vue-particles#45]
How to run vue-particles with typescript?

**Comment by yxbysxcoco** [comment]
I find that they haven't @types/projecrt, so how can we use it with vue/typescript?

**Comment by daviddesmet** [comment]
You can use a quick workaround by creating a new file in your project's root directory:

```ts
// vue-particles.d.ts

declare module "vue-particles" {
  let VueParticles: any;
  export = VueParticles;
}
```

**Comment by musicteachj** [comment]
> You can use a quick workaround by creating a new file in your project's root directory:
> 
> ```ts
> // vue-particles.d.ts
> 
> declare module "vue-particles" {
>   let VueParticles: any;
>   export = VueParticles;
> }
> ```

@idaviddesmet Could you be a little more specific on your solution? I'm running into the same issue.

**Comment by daviddesmet** [comment]
@musicteachj sure! You create a new file named `vue-particles.d.ts` (or any other name, it must end with `.d.ts`) in your root directory (next to your `package.json`, `tsconfig.json`...) and that’s it. 😉

**Comment by musicteachj** [comment]
@idaviddesmet thank you for your response. I put your solution in the root directory like you suggested, but I'm still not having any luck with it. Receiving "Failed to mount component: template or render function not defined." error in the console.

**Comment by musicteachj** [comment]
@idaviddesmet thank you for your response! It looks like I didn't need the .d.ts file after all (they must have updated the lib to not need it), it turns out I was missing the root tag with the id="app" attribute. I am using Vuetify, the installation deletes this tag when adding it to a Vue CLI creation.
