### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by musicteachj** [creotip/vue-particles#60]
Giving error in console from example in https://vue-particles.netlify.com/

Possibly a typescript issue?

**Comment by musicteachj** [comment]
missing id root tag will give this error, vuetify deletes this

**Comment by tuannguyenminh2086** [comment]
how to fix it @musicteachj ?

**Comment by matteobruni** [comment]
Try `particles.vue`, this package is abandoned

https://github.com/matteobruni/tsparticles/blob/master/components/vue/README.md
