### ISSUE TITLE
Could not find a declaration file for module 'vue-particles'

### ISSUE THREAD

**Issue by STV038** [creotip/vue-particles#64]
Hi sir,

Could you please help me with the following issue? 

Could not find a declaration file for module 'vue-particles'. 'app-name/node_modules/vue-particles/src/vue-particles/index.js' implicitly has an 'any' type. Try `npm install @types/vue-particles` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-particles';`ts(7016)

I'm quite at a loss here, since the particle design will not render and the app just throws a blank template

Any help would be much appreciated!

**Comment by TheGreyDiamond** [comment]
So did you manage to fix it? I have the same issue, so....
