### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by RayLuxembourg** [creotip/vue-particles#8]
this package doesn't work as intended .
with current instructions on how to get it working , this wont work.

first issue is babel transform-runtime.

> ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-particles/src/vue-particles/vue-particles.vue
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/itayjoseph/work/devcraft-vue/node_modules/vue-particles/.babelrc" at 0

after you add transfrom-runtime to your babelrc, you will most likely get

> RROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-particles/src/vue-particles/vue-particles.vue
Module build failed: Error: Couldn't find preset "env" relative to directory

this might have worked on previous versions of vue or vue-cli generated boilerplate , but currently  it's not.

Please provide proper instructions on how to use this package without any issues.

**Comment by creotip** [comment]
@itayJoseph 
I just checked vue-particles with the latest version of vue-cli. 
Everything works just fine.
Can you post some more code?

**Comment by itayJoseph** [comment]
hmmm , try using this.
`vue init vuetifyjs/webpack`

**Comment by liCat** [comment]
I have the same problem , almost give up the cool effect.

**Comment by liCat** [comment]
用的webpack,报下面这样的错，请问我要怎么配置一下webpack呢？

>`ERROR in ./~/.6.4.1@babel-loader/lib!./~/.11.3.4@vue-loader/lib/selector.js?type=script&index=0!./~/.1.0.5@vue-particles/src/vue-particles/vue-particles.vue
Module build failed: Error: Couldn't find preset "env" relative to directory "E:\\shaoxia\\my-share\\node_modules\\.1.0.5@vue-particles"`

**Comment by galipmedia** [comment]
Same issue here. Does anyone have a fix for this?

**Comment by galipmedia** [comment]
npm install babel-preset-env --save-dev  fixed it for me

**Comment by hekegang** [comment]
npm install babel-preset-env --save-dev

npm install --save-dev babel-preset-stage-2

**Comment by liurenjie** [comment]
npm install babel-preset-env --save-dev fixed the error for me.
